apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  labels:
    app: {{ template "coturns.name" . }}
    chart: {{ template "coturns.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
data:
  authSecret: {{ default "" .Values.coturns.authSecret | b64enc | quote }}
